server:
  port: 9090

spring:
  application:
    name: wallet-ops
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wallet-balance-group
      enable-auto-commit: false
    producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: org.apache.kafka.common.serialization.JsonSerializer